### ISSUE TITLE
PilosaDriver: Implement AscendIndex and DescendIndex interfaces

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#211]
First of all, we need to modify a bit the existing interface to apply all the changes that we did on the base Index interface. 
- Instead of accepting `key interface{}` we need to modify methods to use `key ...interface{}`. 
- `AscendRange(greaterOrEqual, lessThan interface{}) (IndexLookup, error)` becomes `AscendRange(greaterOrEqual, lessThan []interface{}) (IndexLookup, error)`.

The same changes should be applied to DescendIndex interface.

**Comment by erizocosmico** [comment]
So, I have already implemented the part of getting the ranges, but I hit a very big problem: how to retrieve the results ordered.

There is no way right now to reconstruct the tuple of inserted values from the mapping, so doing it would require N queries to pilosa (one per bit), then ordering in memory and then returning the iterator with these bits ordered. Perhaps this will be slow.

The other option is just to store them ordered in the first place. In pilosa, the columns are stored in arrival order, that is, the first thing the IndexKeyValueIter returned, will have column 0, the next 1, and so on. And the bits resultant of the query will always be returned in that order. By inserting everything indexed we don't have to do anything because they are already ordered. In the case of descend, we just reverse the resultant slice with the bit positions. This also has the advantage of knowing the values in the mapping will also be ordered and you can stop early the iteration of all values to compute the bitmap.
The downside? It needs to sort everything in memory before inserting, which can be quite a lot of things to put in memory.

@ajnavarro what approach do you think we should take? Or if you can think of any other approach, it'd be cool.
