### ISSUE TITLE
Pushdown filters to Tables

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#28]
To filter before hand rows to improve performance, we should push down filters to Tables.

**Comment by erizocosmico** [comment]
Related to #27 

So, proposal for this:

- Add a new interface `SpecializedTable` (name just placeholder) like this:
```
type SpecializedTable interface {
        SpecializedRowIter(projections []Expression, filters []Expression) (RowIter, error)
}
```
- Projections should be kept in the parsing, as well as filters, so they can be passed to the tables.
- Using `TransformUp` we check if any node is a `SpecializedTable` and wrap it with `SpecializedRowProvider` (name is really placeholder). This `SpecializedRowProvider` is created with the projections and filters. When `RowIter` of this node is called, it will call the `SpecializedRowIter` of the table it's wrapping.

### Caveats:

- All nodes should be resolved, which I think are not yet during that phase. Perhaps it doesn't matter because they will be resolved in the analyzer step, but it feels like duplicating jobs, since the same projections and filters will be analyzed twice.
- Perhaps we could add it as a rule instead of during the parse. But that requires gathering the filters and the projections and then doing the transformation, so it's also iterating all over.

Any thoughts? @ajnavarro @mcarmonaa @jfontan

**Comment by ajnavarro** [comment]
Some comments about this:
- actually we have only one phase on the analyzer that resolves all the placeholders if it's possible. for this we need to add another phase after that one to *optimize* the logical plan, with new rules.
- As first iteration of this, all the pushed down filters should be applied two times, one at the table level, another one just above the Table node.
- We can add two interfaces like in spark. One more simpler just to project from the source, and another to project and to filter.

**Comment by jfontan** [comment]
Just so we don't forget we need to know which filters can be applied by the table so they are not applied twice.

**Comment by erizocosmico** [comment]
@jfontan yep, this can be improved with a `UnhandledFilters` method and so on

**Comment by ajnavarro** [comment]
Last proposal as discussed on the design meeting:

Transform methods will change:
- `TransformUp(func(Node) Node) Node` -> `TransformUp(func(sql.Node)(sql.Node, bool)) (sql.Node, error)`
- `TransformExpressionsUp(func(Expression) Expression) Node` -> `TransformExpressionsUp(func(sql.Expresion)(sql.Expression, bool)) (sql.Expression, error)`

Interfaces that can be implemented by table nodes to reduce the amount of data sent to the sql engine:

```go
type PushdownProjectionTable interface {
        WithProject(colNames []string) (RowIter, error)
}
 
type PushdownProjectionAndFiltersTable interface {
        WithProjectionAndFilters(projections []Expression, filters []Expression) (RowIter, error)
        HandledFilters()[]Expression
}
 
type RuntimeTable interface{
        OptimizeTableScan(n sql.Node) (sql.Node, bool)
}
```

We need also to add rules to find the tables that are implementing this interfaces and send the correct data to them.

**Comment by erizocosmico** [comment]
@ajnavarro why the returned errors in the Transform functions? Transform functions _should_ not return errors, right?

**Comment by ajnavarro** [comment]
To have this task done ASAP, let's start implementing proper column resolution first, project and filter pushdown interfaces, and then check if the changes on Transforms are needed for these tasks.
