### ISSUE TITLE
Partitions: Change Indexable interfaces to make use of partitions

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#311]
Base IndexLookup interface will change to be able to get IndexValueIters per Partition.

```go

type IndexLookup interface {
	Values(Partition) (IndexValueIter, error)
}

type IndexableTable interface {
    Table
    WithIndexLookup(IndexLookup) Table
    IndexKeyValues(Context, []string, Partition) IndexKeyValueIter
}

```

**Comment by erizocosmico** [comment]
This is partly done in #329 

Only missing thing is making index drivers work with partitions

**Comment by erizocosmico** [comment]
Since now we have partitions, we should store the partitions in different pilosa frames. Right now, we still send an iterator with everything to the index to create it, so we don't know which rows belong to each partition.

I think we should change the `Save` method of the `IndexDriver` interface to accept a `IndexableTable` instead of an `IndexKeyValueIter`. That way, the driver can iterate partitions and get the `IndexKeyValueIter`s for each partition and save them in different frames.

WDYT @ajnavarro?

**Comment by kuba--** [comment]
Question - shall we add partitions to the driver index (and/or mapping) to quickly get everything  just from particular partition?

**Comment by ajnavarro** [comment]
@erizocosmico  yep, totally needed.

**Comment by erizocosmico** [comment]
@ajnavarro just updated with a second possibility, which one you think it's better?

**Comment by erizocosmico** [comment]
@kuba-- yep

**Comment by erizocosmico** [comment]
I think for now we can get by with not storing info about partitions in the index or mapping. Gitbase can get the partitions from the repository pool and the mem table has them hardcoded, so it's fine for now.
