### ISSUE TITLE
Implement SHOW CREATE TABLE

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-mysql-server#406]
Implement `SHOW CREATE TABLE` statement.

See: https://github.com/src-d/gitbase/issues/361#issuecomment-427285397

**Comment by Zarkopafilis** [comment]
I'll try this

**Comment by Zarkopafilis** [comment]
1) I can't find Charset, Auto increment by number and engine. Should ENGINE default to InnoDB, and DEFAULT CHARSET to `utf8mb4`

I've got to a point where I can print out the basic structure of the statement, but have some issues with the constraints part. [Test run image](https://imgur.com/REpC4h4)

Can you provide some guidance regarding the constraints part?
My bet is that something similar to the following snippet should happen, where you grab the indices and just print the expressions: 
`	indexes := i.registry.IndexesByTable(i.db.Name(), i.table)

	constrCreateStatements := make([]string, len(indexes), len(indexes))
	for indx, index := range indexes {

		createStmtPart := fmt.Sprintf("%s (`%s`)", stripBrackets(index.Expressions()), index.ID())

		if index.Driver() != "" {
			createStmtPart = fmt.Sprintf("%s USING driverid (%s)", createStmtPart, index.Driver())
		}

		constrCreateStatements[indx] = fmt.Sprintf(",\n%s\n", createStmtPart)
	}`

Maybe add a switch on this because:
`	// Expressions returns the indexed expressions. If the result is more than
	// one expression, it means the index has multiple columns indexed. If it's
	// just one, it means it may be an expression or a column.
	Expressions() []string`

**Comment by Zarkopafilis** [comment]
Charset being under conversation on #407

**Comment by smola** [comment]
`ENGINE=InnoDB` by default sounds good, it is the default both for MySQL and MariaDB. Although it's completely fake, users will not be expected to use these CREATE TABLE statements within go-mysql-server itself at the moment.

**Comment by erizocosmico** [comment]
@Zarkopafilis constraints should be empty. go-mysql-server does not create primary keys, foreign keys or unique indexes right now, so they should not show up. The kind of indexes created by go-mysql-server shouldn't show up here.
