### ISSUE TITLE
Modify DESCRIBE to use the sql parser

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#5]
Instead of use a regular expression: 
https://github.com/src-d/go-mysql-server/blob/50166d8f9e431566f0db464f77cc710a92e0a8b3/sql/parse/parse.go#L37

Modify the code to use the standard query to describe the fields of a specific table.

**Comment by erizocosmico** [comment]
Right now, DESCRIBE and EXPLAIN are transformed into `OtherRead` AST Node, which is basically a placeholder with no information about which table should be described. Because of that, changes in go-vitess are required to implement said node.

**Plan of action:**

- Implement a new AST Node in the go-vitess parser that is `DescribeTable`.
- Modify the yacc parser to support it.
- Handle the conversion in go-mysql-server.

**Comment by ajnavarro** [comment]
We can use `SHOW COLUMNS` instead: https://dev.mysql.com/doc/refman/5.7/en/show-columns.html

At least for this preliminary version we must avoid modify the parser, because is automatically obtained from the vitess source code.

**Comment by erizocosmico** [comment]
`SHOW COLUMNS` is not implemented in the parser

**Comment by ajnavarro** [comment]
Related: https://github.com/youtube/vitess/issues/3130

**Comment by erizocosmico** [comment]
In the end it was decided to use `SHOW COLUMNS FROM <table>`
