### ISSUE TITLE
Support sqlparser.Subquery statement

### ISSUE THREAD

**Issue by ajnavarro** [src-d/go-mysql-server#59]

**Comment by erizocosmico** [comment]
Depends on #60

**Comment by erizocosmico** [comment]
Paused until we have a discussion about how to implement this.

**Comment by erizocosmico** [comment]
**Note:** all this only applies to subqueries used as expressions, subqueries used as tables are fine.

## Current approach

The current approach to this was to just wrap a `sql.Node` (which is the subquery itself) and then return a `Tuple` with N elements as a result after collecting all rows in the iterator.

Unfortunately, this approach has a problem: in a subquery used as an expressions you can use columns and tables from outside the query scope.

Example:

```sql
SELECT * 
FROM outer 
WHERE b IN (
    SELECT inner.b 
    FROM inner 
    WHERE inner.a = outer.a
)
```

Currently, there is no way to pass the values of the current row down the execution tree so you can use them.

This approach requires the following changes:

- Be able to pass the row down (actually, not only the row, but all the tables that have been used outside the query).
- When resolving, make sure subqueries also get their columns from outside the scope resolved to the correct column. So, `GetField` wouldn't do it. There has to be another way for this (reference passed via context or idk).

## Another approach

I've been thinking about this for a bit and came up with another solution that I found promising in the beginning but as I got down the rabbit hole has some things missing as well.

Any subquery has, by definition, a `Projection` as its root node in the tree. By transforming the inner tree we could transform the table/tables to be a cross join of the table and another "virtual table" with just one row: the current row. Then, the projection will take care of selecting only what the user wrote in the select.

Of course, this has problems as well:
- How to deal with the cross join when there is already any join inside the subquery?
- How to get the row (which actually should be all available tables in scope) down to the cross join.

### Things to take into consideration

Result of a subquery can only be one of the following things:

- A tuple, one element for each resultant row. Each row can have one and only one column.
- A single row with one column.

**Comment by ajnavarro** [comment]
Postponing the implementation of subqueries for future versions.

**Comment by erizocosmico** [comment]
### Idea

Add an optimizer rule to do the following:

- Look for the topmost `sql.Table`, `plan.InnerJoin` or `plan.CrossJoin` and wrap it with a `CachedNode` (which will cache the results of that query for subsequent uses). We could search for all used columns to put a projection before the CachedNode and minimize the amount of data cached.
- Wrap the `CachedNode` with a `CrossJoin` with a `RowNode` (which returns always the same row)

Then on evaluation:

- Every time we call `Subquery.Eval` we `plan.Inspect` the subquery tree and change the `sql.Row` of the `RowNode` with `SetRow`. Because `CachedNode` keeps the results of the subquery cached, the result is not _that_ expensive in subsequent runs.
- We collect the rows as a tuple.

**Comment by erizocosmico** [comment]
# Implementing subqueries on go-mysql-server

Some queries become hard to read or write without proper support for subqueries. We already have support for them in the `FROM` statement, but we lack support for them as expressions.

## Current problems

- No way to pass the current row of the parent query to an expression.
- No way to resolve a query using columns from the parent query.

## Solution

Add the concept of a parent scope and pass it along using the `Context` that every single node receives.

### Parsing

Convert the currently unsupported node for a subquery to a `Subquery` node. Should be pretty straightforward.

### Changes in Context

Context needs to have two new functionalities:

- Providing the parent row, if any. If there is more than 1 ancestor, also access to them.
- Providing the parent schema, if any. If there is more than 1 ancestor, also access to them.

```go
type Context struct {
    // ...
    parentRow Row
    parentSchema Schema
}

func (ctx *Context) clone() *Context {
    var newCtx Context
    // clone all other properties

    if ctx.parentRow != nil {
        newCtx.parentRow = make(Row, len(ctx.parentRow))
        copy(newCtx.parentRow, ctx.parentRow)
    }

    if ctx.parentSchema != nil {
        newCtx.parentSchema = make(Schema, len(ctx.parentSchema))
        copy(newCtx.parentSchema, ctx.parentSchema)
    }

    return newCtx
}

func (ctx *Context) WithParentRow(row Row) *Context {
    newCtx := ctx.clone()
    // by appending, we allow access to all ancestors
    newCtx.parentRow = append(newCtx.parentRow, row)
    return newCtx
}

func (ctx *Context) ParentRow() (Row, error) {
    if ctx.parentRow == nil {
        return nil, ErrNoParent
    }
    return ctx.parentRow, nil
}

func (ctx *Context) WithParentSchema(s Schema) *Context {
    newCtx := ctx.clone()
    // by appending, we allow access to all ancestors
    newCtx.parentSchema = append(newCtx.parentSchema, s)
    return newCtx
}

func (ctx *Context) ParentSchema() (Schema, error) {
    if ctx.parentSchema == nil {
        return nil, ErrNoParent
    }
    return ctx.parentSchema, nil
}
```

### Resolution

When resolving a column and failing to do so, there will be a fallback to try and resolve said column using the parent scope, if any. That column will be replaced with `GetParentField` node, a special node that will retrieve values from the rows in the parent.

```go
type GetParentField struct {
    table string
    name string
    index string
}
```

Esentially, all rules that convert from an `UnresolvedColumn` to `GetField` or similar, must be changed in order to account for this new logic.

A new rule `resolve_subqueries` must be added where they are resolved after adding the current node schema to the context and pass it down.

### Execution

`Subquery` will be an `Expression` and will execute as any other, except it will do the following in its `Eval` method.

```go
func (s *Subquery) Eval(ctx *sql.Context, row sql.Row) (interface{}, error) {
    iter, err := s.Query.RowIter(ctx.WithParentRow(row))
    if err != nil {
        return nil, err
    }

    rows, err := sql.RowIterToRows(iter)
    if err != nil {
        return nil, err
    }

    switch len(rows) {
    case 0:
        return nil, ErrSubqueryExpectedRows.New()
    case 1:
        return rows[0][0], nil
    default:
        var values = make([]interface{}, len(rows))
        for i, row := range rows {
            values[i] = row[0]
        }

        return values, nil
    }
}
```

A subquery can either return a single value or a tuple with many values. For further improvement, this could be a generator (we already have that interface) and `IN` and so on could either take values, a tuple or a generator, etc.

**Caveats:** How to properly return in `Type` method if we don't know whether it will return a value or a tuple until `Eval`? An option could be to use Array instead of Tuple in this case.

And then, `GetParentField` will execute as follows:

```go
func (f *GetParentField) Eval(ctx *sql.Context, row sql.Row) (interface{}, error) {
    parentRow, err := ctx.ParentRow()
    if err != nil {
        return nil, err
    }

    if len(parentRow) < f.Index {
        return nil, someerror
    }

    return parentRow[f.Index], nil
}
```

## gitbase-spark-connector-enterprise

Will require changes as well in order to push down subqueries, but the changes should be pretty straight-forward as well.
