### ISSUE TITLE
LEFT OUTER JOIN support

### ISSUE THREAD

**Issue by smola** [src-d/go-mysql-server#707]
LEFT OUTER JOIN support would be nice.

For gitbase, this might be used to check repositories where a given file is absent. Note that for the use cases I'm trying, getting the LEFT OUTER JOIN resolved in Spark with gitbase-spark-connector would be just fine.

**Comment by erizocosmico** [comment]
Note that squash rule cannot be applied to left outer join, so even if we implement it, it's going to be significantly slower than an inner join because of that limitation.

With an inner join we know we can have table B derived from table A knowing the relationship between A and B. But if we have to account for all possible values of B, it can't be, so it essentially becomes a cross join with some null columns if a condition is not met.

**Comment by smola** [comment]
@erizocosmico I thought a LEFT JOIN could theoretically be squashed if the left table is previous in the iterator chain?

**Comment by erizocosmico** [comment]
After a deeper thought, yes, in that case it can. It will need a bit of a refactor to make it work, but yes
